# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS and Python version to match your project.
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    install:
      # Install pixi, dependencies, and the project in one block
      # to ensure the PATH is set correctly for all commands.
      - |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        export PATH="$HOME/.local/bin:$PATH"
        uv venv
        .venv/bin/uv pip install -e .[docs]
    build:
      html:
        - |
          export PATH="$HOME/.local/bin:$PATH"
          .venv/bin/uv run sphinx-build -b html docs/ $READTHEDOCS_OUTPUT/html

# The sphinx key is removed to prevent Read the Docs from running
# its own build command, which would use the wrong environment. 