# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS and Python version to match your project.
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    install:
      # Install pixi using the official installer script
      - curl -fsSL https://pixi.sh/install.sh | bash -s -- --yes
      # Add pixi to the PATH and install project dependencies and the project itself.
      # This is run as a single command to ensure the PATH is set correctly.
      - |
        export PATH="$HOME/.pixi/bin:$PATH"
        pixi install --frozen
        pixi run pip install .

# Build the documentation
sphinx:
  configuration: docs/conf.py
  # Fail on all warnings to avoid broken references
  fail_on_warning: true 
