version: 2

# Specify the build environment
build:
  os: ubuntu-22.04  # Using a recent LTS version of Ubuntu
  tools:
    python: "3.9"   # Ensure this matches your project's Python version

# Configure Sphinx
sphinx:
  configuration: docs/conf.py
  # fail_on_warning: true # Uncomment this to make builds fail on any Sphinx warning

# Configure Python environment and dependencies
python:
  install:
    - method: pip
      path: .  # This installs your project (bnl)
      extra_requirements:
        - docs # This installs dependencies from [project.optional-dependencies.docs] in pyproject.toml

