# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS and Python version to match your project.
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_install:
      # Install pixi, then install project dependencies from pixi.lock
      - conda install -c conda-forge pixi
      - pixi install --frozen
      # Install the project itself so Sphinx can read its version
      - pixi run pip install .

# Build the documentation
sphinx:
  configuration: docs/conf.py
  # Fail on all warnings to avoid broken references
  fail_on_warning: true 