version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

# Build documentation with the "readthedocs" requirements
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Optionally set the version of Python required.
# We recommend setting this to the same version as your local development environment
# to avoid any differences in behavior.
#
# For a list of supported Python versions on Read the Docs, see:
# https://docs.readthedocs.io/en/stable/builds.html#build-environments

# Optionally build your docs in additional formats such as PDF and ePub
formats: []  # Disable PDF and other formats
