# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS and Python version to match your project.
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      # Install the project itself so Sphinx can import it to generate docs.
      # This command runs after pixi has installed the other dependencies.
      - python -m pip install .

# Tell Read the Docs to use pixi to install dependencies.
pixi:
  install:
    # The "default" environment in your pixi.toml includes all necessary 
    # dependencies for the documentation.
    - --environment default

# Configure the Sphinx build.
sphinx:
  configuration: docs/conf.py
  # Fail on all warnings to avoid broken references
  fail_on_warning: true 