name: py311
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  # Core dependencies (stable versions from conda)
  - numpy>=1.20
  - matplotlib>=3.3
  - librosa>=0.8.0
  - pyarrow>=14.0
  - seaborn>=0.13.2
  
  # Docs dependencies
  - sphinx>=4.0
  - sphinx-rtd-theme>=0.5.0
  - numpydoc>=1.0
  - sphinx-copybutton>=0.3.0
  - myst-parser>=0.18.0
  - sphinx-autobuild>=2021.3.14
  
  # Notebook dependencies
  - jupyter
  - ipykernel
  
  # Dev dependencies
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - black>=23.0.0
  - isort>=5.0.0
  - mypy>=0.910
  - pylint>=2.12.0
  - pip # Needed for pip install commands

  # Development versions from GitHub (using pip)
  - pip:
    - git+https://github.com/marl/jams.git
    - git+https://github.com/craffel/mir_eval.git