name: py311
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  # Core dependencies from pyproject.toml
  - numpy>=1.20
  - mir_eval>=0.7
  - matplotlib>=3.3
  - librosa>=0.8.0
  - pyarrow>=14.0
  # Docs dependencies from pyproject.toml
  - sphinx>=4.0
  - sphinx-rtd-theme>=0.5.0
  - numpydoc>=1.0
  - sphinx-copybutton>=0.3.0
  - myst-parser>=0.18.0
  - sphinx-autobuild>=2021.3.14
  # Dev dependencies
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - pip # Needed for pip install commands later 