name: bnl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  
  # Core dependencies (stable versions from conda)
  - numpy
  - matplotlib
  - librosa
  - pyarrow
  - seaborn
  - mir_eval
  
  # Docs dependencies
  - sphinx
  - sphinx-rtd-theme
  - numpydoc
  - sphinx-copybutton
  - myst-parser
  - sphinx-autobuild
  
  # Notebook dependencies
  - jupyter
  - ipykernel
  
  # Dev dependencies
  - pytest
  - pytest-cov
  - black
  - isort
  - mypy
  - pylint
  - pip # Needed for pip install commands

  # Development versions from GitHub (using pip)
  - pip:
    - git+https://github.com/marl/jams.git