[project]
name = "bnl"
version = "0.2.1"
description = "Boundary and Labeling: Tools for Hierarchical Music Structure Analysis"
authors = ["tomxi <tom.xi@nyu.edu>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[system-requirements]

[dependencies]
# Core dependencies
numpy = "*"
matplotlib = "*"
librosa = "*"
pyarrow = "*"
seaborn = "*"
mir_eval = "*"

# Runtime dependencies
python = "3.12.*"
requests = ">=2.32.4,<3"
ffmpeg = ">=7.1.1,<8"

[host-dependencies]
pip = "*"

[build-dependencies]
setuptools = ">=61.0.0"
wheel = "*"

[pypi-dependencies]
jams = "*"

[feature.docs.dependencies]
# Documentation dependencies
sphinx = "*"
sphinx-rtd-theme = "*"
numpydoc = "*"
sphinx-copybutton = "*"
myst-parser = "*"
sphinx-autobuild = "*"

[feature.dev.dependencies]
# Development dependencies
# We've removed pylint to consolidate on ruff for speed and simplicity.
pytest = "*"
pytest-cov = "*"
ruff = "*"
mypy = "*"
types-requests = "*"
requests-mock = "*"

[feature.notebooks.dependencies]
# Notebook dependencies
jupyter = "*"
ipykernel = "*"

[feature.apps.dependencies]
# Dependencies for running some interactive apps or widgets
streamlit = "*"

[feature.cloud.dependencies]
boto3 = ">=1.38.44,<2"

[environments]
default = ["docs", "dev", "notebooks", "apps"]
minimal = []
docs = ["docs"]
dev = ["dev"]
notebooks = ["notebooks"]
apps = ["apps"]
cloud = ["cloud"]

[tasks]
# ===================================================================
# Primary Workflow: Format, Fix, Check, Test
# ===================================================================

# Auto-formats all code in the project. Run this often.
format = "ruff format ."

# Lints the code and automatically fixes any safe violations.
fix = "ruff check . --fix"

# Verifies code is formatted and passes linting checks (ideal for CI).
check = "ruff format --check . && ruff check ."

# Runs all tests using pytest.
test = "pip install -e . && pytest"

# ===================================================================
# In-depth & Optional Tasks
# ===================================================================

# Runs tests and generates a code coverage report in the terminal.
test-cov = "pytest --cov=bnl --cov-report=term-missing"

# Runs mypy for static type analysis. Can be slow on large codebases.
# Kept separate from the main 'check' task for a faster core loop.
types = "mypy src/ --ignore-missing-imports"

# Builds the cloud manifest with full asset URLs for R2 deployment.
# This task now requires the 'cloud' environment.
# Run with: pixi run -e cloud build-cloud-manifest
build-cloud-manifest = "python scripts/build_cloud_manifest.py"

# Runs the Streamlit experiment app.
exp = "streamlit run ./apps/exp.py"

# Builds the local manifest for your project.
build-local-manifest = "python scripts/build_local_manifest.py"

# ===================================================================
# Documentation
# ===================================================================

# Builds the Sphinx documentation into the docs/_build/html directory.
docs-build = "sphinx-build -b html docs docs/_build/html"

# Serves the documentation with live-reloading for easy editing.
docs-serve = "sphinx-autobuild docs docs/_build/html --host 127.0.0.1"

# Cleans out the built documentation files.
docs-clean = "rm -rf docs/_build"
