[project]
name = "bnl"
version = "0.2.1"
description = "Boundary and Labeling: Tools for Hierarchical Music Structure Analysis"
authors = ["tomxi <tom.xi@nyu.edu>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[system-requirements]

[dependencies]
# Core dependencies
numpy = "*"
matplotlib = "*"
librosa = "*"
pyarrow = "*"
seaborn = "*"
mir_eval = "*"

# Runtime dependencies
python = "3.12.*"
requests = ">=2.32.4,<3"
ffmpeg = ">=7.1.1,<8"

[host-dependencies]
pip = "*"

[build-dependencies]
setuptools = ">=61.0.0"
wheel = "*"

[pypi-dependencies]
jams = "*"

[feature.docs.dependencies]
# Documentation dependencies
sphinx = "*"
sphinx-rtd-theme = "*"
numpydoc = "*"
sphinx-copybutton = "*"
myst-parser = "*"
sphinx-autobuild = "*"

[feature.dev.dependencies]
# Development dependencies
# We've removed pylint to consolidate on ruff for speed and simplicity.
pytest = "*"
pytest-cov = "*"
ruff = "*"
mypy = "*"
types-requests = "*"
requests-mock = "*"
pytest-mock = "*"

[feature.notebooks.dependencies]
# Notebook dependencies
jupyter = "*"
ipykernel = "*"

[feature.apps.dependencies]
# Dependencies for running some interactive apps or widgets
streamlit = "*"

[feature.cloud.dependencies]
boto3 = ">=1.38.44,<2"

[environments]
default = ["docs", "dev", "notebooks", "apps"]
minimal = []
docs = ["docs"]
dev = ["dev"]
notebooks = ["notebooks"]
apps = ["apps"]
cloud = ["cloud"]

[tasks]
# ===================================================================
# Core Development Loop
# ===================================================================

# Format source code (run frequently during development)
format = "ruff format src/ apps/"

# Check code style without fixing (useful for CI)
lint = "ruff check src/ apps/"

# Fix code style issues automatically
fix = "ruff check src/ apps/ --fix"

# Run all tests
test = "pip install -e . && pytest"

# Run full validation pipeline (format + lint + types + test)
check = "pip install -e . && ruff format --check src/ apps/ && ruff check src/ apps/ && mypy src/ apps/ --ignore-missing-imports && pytest"

# ===================================================================
# Extended Development Tasks
# ===================================================================

# Run tests with coverage report
test-cov = "pip install -e . && pytest --cov=bnl --cov-report=term-missing"

# Type checking only (faster when you just need types)
types = "mypy src/ apps/ --ignore-missing-imports"

# Clean build artifacts and cache  
clean = "rm -rf build/ dist/ .pytest_cache/ .coverage .mypy_cache/ src/**/__pycache__/ tests/**/__pycache__/ *.egg-info/ || true"

# ===================================================================
# Application & Data Tasks
# ===================================================================

# Run the Streamlit experiment app
exp = "streamlit run ./apps/exp.py"

# Build local data manifest for development
build-local-manifest = "python scripts/build_local_manifest.py"

# Build cloud manifest with R2 URLs (requires cloud environment)
# Usage: pixi run -e cloud build-cloud-manifest
build-cloud-manifest = "python scripts/build_cloud_manifest.py"

# ===================================================================
# Documentation Tasks
# ===================================================================

# Build documentation (output to docs/_build/html)
docs-build = "sphinx-build -b html docs docs/_build/html"

# Serve docs with live reload for development
docs-serve = "sphinx-autobuild docs docs/_build/html --host 127.0.0.1"

# Clean documentation build artifacts
docs-clean = "rm -rf docs/_build"
