[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bnl"
version = "0.2.0"
description = "Boundary and Labeling: Tools for Hierarchical Music Structure Analysis"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
dependencies = [
    "numpy",  
    "matplotlib",
    "librosa",
    "pyarrow",
    "seaborn",
    "mir_eval",
    "jams @ git+https://github.com/marl/jams.git"
]

[project.optional-dependencies]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
    "numpydoc",
    "sphinx-copybutton",
    "myst-parser",
    "sphinx-autobuild",
]
dev = [
    "pytest",
    "pytest-cov",
    "black",
    "isort",
    "mypy",
    "pylint",
]

[project.urls]
Source = "https://github.com/tomxi/bnl"
Issues = "https://github.com/tomxi/bnl/issues"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
filterwarnings = [
    "ignore::DeprecationWarning:jsonschema.*",
]

[tool.coverage.run]
source = ["src"]
omit = ["tests/*"]
relative_files = true

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "^\\s*def __repr__",
    "raise NotImplementedError",
    "^if __name__ == ['\"]__main__['\"]:",
    "^\\s*pass$",
    "raise ImportError"
]
fail_under = 80
