name: bnl-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - sphinx>=4.0
  - sphinx-rtd-theme>=0.5.0
  - sphinx-copybutton>=0.3.0
  - numpydoc>=1.0
  - myst-parser>=0.18.0
  - pip:
    - -r requirements.txt
